### ISSUE TITLE
第1回（2021-07-31まで募集中）の告知をUbuntu界隈にもだしてみよう

### ISSUE THREAD

**Issue by kenhys** [oss-gate/on-boarding#14]
Debian界隈だけじゃなくて、Ubuntu界隈にも告知を検討する。
対象はUbuntu関連の人ということで https://lists.ubuntu.com/mailman/listinfo/ubuntu-jp に案内を流すことを想定。

```

Subject: Debian/Ubuntuプロジェクトに継続的に関わり始めたい人募集のお知らせ

OSS Gateオンボーディングという取り組み [1] のなかで
Debian/Ubuntuプロジェクトに継続的に関わり始めたい(けどまだ手を動かせていない)人を募集 [2] して、
いっしょに開発をしたりするというのをやってみようとしています。
7月末まで募集して、8月から10月にかけて実施できればと考えています。

  詳しい内容および応募方法はこちら
  https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/#how-to-apply

いくつかコースを用意しているうち、「Aコース: 新規Debianパッケージング作業」については
実施する内容はUbuntuでも活かせるはずのものなので、こちらのメーリングリストでお知らせすることにしました。

* 例: PPAに置いているパッケージがある(いい感じにしたい)
  * ↑の取り組みでいっしょにDebianにパッケージをもっていけるようにしましょう！

募集の締切はいったん7/31(土)までとしていますが、もうすこし詳細を知りたいとか
実施期間が都合が悪くて応募できないでいる等、興味があるレベルであってもよいのでご相談ください。
相談窓口は問い合わせ方法に記載のとおり on-boarding@oss-gate.org です。

  問い合わせ方法:
  https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/#how-to-inquiry

今月のDebian勉強会(7/17)で趣旨を話す機会があった [3] ので @debianjp とか @debian_jp でも
紹介してもらった [4] のでそちら方面にはある程度届いていそうなのですが、Ubuntu界隈はそうでもなさそうです。
もしまわりにこの取り組みに興味を持ちそうな人候補がいたら教えてあげたりとか、
[5] のツイートをリツイートして広めてもらえると助かります。

[1] OSS Gateオンボーディングについて
https://oss-gate.github.io/on-boarding/about/

[2] Debianパッケージのメンテナンスやそれを支えるシステムの開発
https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/

[3] 2021年7月の東京エリア・関西合同Debian勉強会の発表資料
https://slide.rabbit-shocker.org/authors/kenhys/tokyodebian-oss-gate-onboarding-20210717/

[4]
https://twitter.com/debianjp/status/1415886001159823361
https://twitter.com/debian_jp/status/1416310976396156928

[5]
https://twitter.com/kenhys/status/1419552644817776641
```

**Comment by kou** [comment]
> Debianプロジェクトに継続的に関わりたい新人さんを募集 [2] して、

Debian/Ubuntuプロジェクトにするのはどうですか？

**Comment by kou** [comment]
「新人さん」はオンボーディング内の用語なので

Debian/Ubuntuプロジェクトに継続的に関わり始めたい（けどまだ手を動かせていない）人を募集

みたいな感じはどうですか？

**Comment by kenhys** [comment]
> Debian/Ubuntuプロジェクトにするのはどうですか？

↑のほうがよさそうですね！

**Comment by kou** [comment]
https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/ もUbuntuもいける感じに調整してもらえますか？

**Comment by kenhys** [comment]
> https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/ もUbuntuもいける感じに調整してもらえますか？

わかりました！

**Comment by kou** [comment]
リツイート対象の↓なんですが、Ubuntuもいけるよ感がないので、林さんが一発Ubuntuもいけるよ感とか応募の手前の興味がある人も`on-boarding@oss-gate.org`に連絡してね感をだしたツイートをしてそれをリツイート願いするのはどうですか？
https://twitter.com/debianjp/status/1415886001159823361
https://twitter.com/debian_jp/status/1416310976396156928

**Comment by kenhys** [comment]
> > https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/ もUbuntuもいける感じに調整してもらえますか？

反映済み https://github.com/oss-gate/on-boarding/pull/15

**Comment by kenhys** [comment]
https://twitter.com/kenhys/status/1419552644817776641 をリツイートして広めてもらえないか文言変更。

**Comment by kou** [comment]
では、これで告知しましょう！

**Comment by kenhys** [comment]
告知を出した。
https://lists.ubuntu.com/archives/ubuntu-jp/2021-July/006451.html
