### ISSUE TITLE
プロセス：活動場所について書く

### ISSUE THREAD

**Issue by kou** [oss-gate/on-boarding#16]
対象OSSにもよるけど、新人と先輩はできるだけその対象OSSの標準的に使われている場所を使ってコミュニケーションをとることみたいなことをどこかに書いておきたい。

たとえば、TwitterとかチャットツールのDMで個人的にやりとりするよりもissue/pull request/merge request/mailing listなどを使ってやりとりするとか。

OSS Gateオンボーディング後も新人が対象OSSの開発に継続的に参加するためには標準的に使わている場所に慣れた方がいいから。

**Comment by kenhys** [comment]
https://oss-gate.github.io/on-boarding/process/ に活動場所を追加したのでとじる。
