### ISSUE TITLE
プロセス：各課題に関する情報のまとめ方をとりまとめる

### ISSUE THREAD

**Issue by yoshimotoyuk** [oss-gate/on-boarding#21]
* 募集要項
* 日報
* レポート

など段階によってでてくる様々な記録をどうやってわかりやすくアクセスできるようにいていくかを検討する。

**Comment by kenhys** [comment]
この問題提起はindex.mdの内容がどんどん増えてきたことによるもの。

例: https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/

このようになったのは、もともと募集要項のページに付け足していったという背景があるため。
すでに実施済みの募集時の告知等で参照しているので今回はここに集約した状態のままだが、
第2回以降はわかりやすくしたいというのが起票した動機、だったはず。

**Comment by kenhys** [comment]
募集要項を分離したテンプレページを追加した。
https://oss-gate.github.io/on-boarding/proposals/YYYY-MM/template/
募集要項のテンプレートページは以下に移動した。
https://oss-gate.github.io/on-boarding/proposals/YYYY-MM/template/proposal.html

上記ページへは https://oss-gate.github.io/on-boarding/process/#section-1 からたどれるようにしてある。
募集をはじめるにあたっては proposals/YYYY-MM/template/ をまるっとコピーして自分の提案を作れば良い。

**Comment by yoshimotoyuk** [comment]
一連の流れが終わって必要なページとその状況などについてのまとめ

* オンボーディングindex page
  * About　・・・　プロジェクトに関する説明、目的、どんな人が関わるか
  * プロセス　・・・オンボーディング自体のすすめかたについて
    * 日報：what is and how to write Daily Report
    * ミーティング：what is and how to write Meeting report
    * 最終レポート：how to write Final report
  * 質問 　・・・　よくある質問とその回答。TODO : UPDATE the FAQ
  * 募集中のプロジェクト
  * 開催中のプロジェクト
  * 過去のプロジェクト
ーーーーー  

* 募集要項
     * ステータス
     * 最終レポート
     * 日報
     * ミーティングレポート
     * 参考資料
     * 募集要項（最初の分）
 
-----------

募集要項のテンプレートは作ってもらえたので、
実際に開催が始まったら目次を頭につけ項目増やすようにするのがいいのかも

最終レポートは、
indexの募集終了から飛べるようになっていてもいいのかも？（次の人へのお誘いになるかもしれないから。もしくはそうなるようにインデックスに＊過去レポートのリンクはつくるのがいいのかも）

**Comment by yoshimotoyuk** [comment]
![image](https://user-images.githubusercontent.com/86996282/136933994-83ce927d-3a6f-4db8-9102-b44c5083078f.png)
次の募集の前にtopにオンボーディングも追加してもらうのはどうか

**Comment by kenhys** [comment]
> 最終レポートは、indexの募集終了から飛べるようになっていてもいいのかも？

よさそうなので、リンクを追加しました。

![image](https://user-images.githubusercontent.com/225841/137068407-ae1629b4-ec0b-4c31-8989-30a9ebe231ac.png)

**Comment by kenhys** [comment]
https://oss-gate.github.io/ でワークショップレポートにならって、オンボーディングのレポートがまとまっているページへの導線を追加。

![image](https://user-images.githubusercontent.com/225841/137069735-d4ddeca4-4860-4ca0-9321-a964e5646865.png)

**Comment by kenhys** [comment]
/on-boarding/への導線がなかったので追加。

![image](https://user-images.githubusercontent.com/225841/137070864-1157ef13-6910-443a-bf17-df898a92b79a.png)

**Comment by yoshimotoyuk** [comment]
林さんすごい・・・

**Comment by kenhys** [comment]
フッタからは記事一覧でたどることになっているんだけど、これはこのままでもいいかな。

![image](https://user-images.githubusercontent.com/225841/137071196-df8823b2-f304-48c9-b027-0a7928141bc4.png)

**Comment by yoshimotoyuk** [comment]
フッターはいったん良いとおもいました！

**Comment by kenhys** [comment]
https://oss-gate.github.io/on-boarding/qa/ にTOCを追加。

**Comment by kenhys** [comment]
スポンサーなりたい、先輩役やりたいなど、窓口を `on-boarding@oss-gate.org` としておいた。

**Comment by kou** [comment]
OSS Gateワークショップとの違いは下に置いておいてもらえますか？

たぶん、OSS Gateオンボーディングに参加する人はそもそもOSS Gateワークショップを知らない人の方が多いので、あえて似たようなものがある（そんなに似ていないけど）ことがあることを匂わして混乱させたくないです。

**Comment by kenhys** [comment]
> OSS Gateワークショップとの違いは下に置いておいてもらえますか？

なるほど、わかりました！

**Comment by kenhys** [comment]
> OSS Gateワークショップとの違いは下に置いておいてもらえますか？

修正済み。あとでうっかりまた似たような変更をしないように意図をコメントとして残しておいた。

**Comment by kenhys** [comment]
https://oss-gate.github.io/on-boarding/about/ 概要に先輩のメリットとして知識のアップデートできることを追加。

**Comment by kenhys** [comment]
TODO:

* https://oss-gate.github.io/on-boarding/about/  関係図。これは @yoshimotoyuk さんがたぶんいい感じのを用意してくれるはず

@yoshimotoyuk あとここ更新したほうがよいところって何か気づいたところありますか?

**Comment by yoshimotoyuk** [comment]
おす、頑張って図作ってみますね
すいませんお任せしっぱなしで
ありがとうございました。

**Comment by kenhys** [comment]
@yoshimotoyuk おねがいします！

**Comment by yoshimotoyuk** [comment]
![relationship1](https://user-images.githubusercontent.com/86996282/137883376-3b572d3f-e4e2-42d5-b06c-030a1229cfed.png)
![image](https://user-images.githubusercontent.com/86996282/137883686-e727d4ab-aae2-4605-80a6-4ca975b6868d.png)

いったん2パターン考えてみました
ちょっと説明的な言葉も入れたパターンと
単純な関係図みたいな感じです。

ここでは役割のところにいれるので単純な関係図が良いのかな・・・

**Comment by yoshimotoyuk** [comment]
うぉ背景投下しているので修正版を・・

**Comment by yoshimotoyuk** [comment]
![relationship2](https://user-images.githubusercontent.com/86996282/137884088-379edf06-d3f6-49de-bd36-5d2e16c48f24.png)

**Comment by yoshimotoyuk** [comment]
トリミングとはちゃんとするということで・・・

**Comment by kenhys** [comment]
> ここでは役割のところにいれるので単純な関係図が良いのかな・・・

@yoshimotoyuk  ということでこちらを入れてみました。

![image](https://user-images.githubusercontent.com/225841/138017535-2c34ad93-b3e5-496f-aa6f-08189461b325.png)

**Comment by kenhys** [comment]
各進行状況ごとに必要になるもののおさらい。次回開催の観点でほぼ必要な情報はでそろっているはず。

募集開始
* https://oss-gate.github.io/on-boarding/process/ 連絡してもらう & 先輩がPRだす旨の説明あり
* 募集要項のテンプレートもリンクあるのでそれを使ってもらえば良い状態になっている
* 募集のブラッシュアップについてはPRでやりとりすればよい
* 告知をどうするかあたりはon-boarding-applicationに先輩を誘導すればよい (-applicationについて説明いる?)

応募開始
* 新人さん: https://oss-gate.github.io/on-boarding/ いまは募集していないけど、トップに導線あり
* 募集要項をテンプレにしたがって書いてもらえば、応募の判断に必要な情報は提供できるはず
* 選考は on-boarding-application で先輩にやってもらえばよい

開発開始
* 日報、ミーティング、最終レポートのテンプレは準備あり
* 進め方は募集要項で決めているので、それにしたがってやってもらえばいいはず。ふりかえりで必要に応じて微調整するくらい? 

全体:
* スポンサーに限らず問い合わせは on-boarding@oss-gate.org に誘導している 
* issueでも受け付ける?

**Comment by yoshimotoyuk** [comment]
まとめありがとうございます！

進行状況について結果として下記になった気がします。
いろんな募集がありすぎて「募集」だとわかりづらいので小分けにしただけ説。

①　スポンサー募集（先輩を出してくれるOSS開発を推進したい会社）
　　
②　先輩への説明会と募集要項作成
林さんの書いてくださった下記で基本差し支えない＋先輩によっては不要そうですが、
ここまでのいろんな話の流れだと、いったん先輩に簡単な説明をしてあげたほうがよさそう
伝えることは林さんが書いてくださったことにプラスしてこんな仮名を追加しました。
*  流れとかテンプレとかの紹介
*  やり取りの仕方
*  選考のやり方（-Application リポジトリーの紹介）（私正しくリポジトリー使いました？）
*  あと新人さんが決まった後に、最初のMTGまでに確認しないといけないことがあることを伝えるとか（環境とか、事前に作る必要のあるアカウントがいりそうとか）
*  成果発表について（これはスポンサーの意思もありそうですが、Debianみたいな勉強会が対象OSSにあるかないかとかもあるとおもうので、先輩としてどういう可能性があるのか、教えてもらったほうがいいのかなっておもいました）

>     * https://oss-gate.github.io/on-boarding/process/ 連絡してもらう & 先輩がPRだす旨の説明あり
> 
>     * 募集要項のテンプレートもリンクあるのでそれを使ってもらえば良い状態になっている
> 
>     * 募集のブラッシュアップについてはPRでやりとりすればよい
> 
>     * 告知をどうするかあたりはon-boarding-applicationに先輩を誘導すればよい (-applicationについて説明いる?)

③　新人さんの募集開始
*  新人募集の手伝いもよろしくとスポンサーと先輩には説明しておいたほうがいいかも
 >     * 新人さん: https://oss-gate.github.io/on-boarding/ いまは募集していないけど、トップに導線あり
> 
>     * 募集要項をテンプレにしたがって書いてもらえば、応募の判断に必要な情報は提供できるはず
> 
>     * 選考は on-boarding-application で先輩にやってもらえばよい

④　新人さんの応募と選考　
 * 選考期間はある程度用意しておく
 * 選考の返事用のテンプレ文章→前回作ったのをapplicationのリポジトリーに入れておこう
 * 先輩に、こんな応募に対しての返事にやり取り発生するかもしれないことも説明しておくといいかも（林さんが、おすすめのリンクとか勉強会と出してくださった感じのやつ）

⑤ 開発開始
* 最初のミーティング用の説明スライド　準備OK
* 最初のミーティング用のテンプレは改めて準備する（通常のふりかえりと一緒だとだめだった）
> 
>     * 日報、ミーティング、最終レポートのテンプレは準備あり
> 
>     * 進め方は募集要項で決めているので、それにしたがってやってもらえばいいはず。ふりかえりで必要に応じて微調整するくらい?
　→進め方はおっしゃる通りだとおもいますー！



> 全体:
> 
>     * スポンサーに限らず問い合わせは [on-boarding@oss-gate.org](mailto:on-boarding@oss-gate.org) に誘導している
> 
>     * issueでも受け付ける?
→issueでも受け付けたほうがいいのかも・・・？

なんかいろいろかいてみました。
どうでしょうか。。。

**Comment by kenhys** [comment]
> →issueでも受け付けたほうがいいのかも・・・？

ひとまず、テンプレを用意してみました。

![image](https://user-images.githubusercontent.com/225841/138066371-a088155e-b13c-420a-8eba-5df1d80acef8.png)

**Comment by yoshimotoyuk** [comment]
すごい！

**Comment by kenhys** [comment]
@yoshimotoyuk 
https://github.com/oss-gate/on-boarding/issues/21#issuecomment-947455794 のフィードバックをおおまかな流れに
反映しました。
先輩への説明会についてはベージをわけて、
https://oss-gate.github.io/on-boarding/process/briefing/mentor.html としてみました。

**Comment by kenhys** [comment]
> 最初のミーティング用のテンプレは改めて準備する（通常のふりかえりと一緒だとだめだった）

あとは、↑だけど別isssue (applicationの#9) ですすめているので、このissueはいったん閉じてよいはず。
