### ISSUE TITLE
2021-08: 10/06(水) の作業予定

### ISSUE THREAD

**Issue by kenhys** [oss-gate/on-boarding#27]
* ふりかえり（まとめ）MTG
  * 開催予定日：2021年10月6日 11:30-13:30
  * 開催時間：90分予定（ふりかえり60分＋発表や今後についてのラップアップ　30分）
　前回のふりかえりが60分でぴったりだったので、それと別に発表やラップアップについての説明の時間を想定しています。
* 時間があまったら何か作業するかも

作業状況:

* [DMD](https://udd.debian.org/dmd/?email1=shibuuuu5%40gmail.com&email2=&email3=&packages=&ignpackages=&format=html#todo)
* [DDPO](https://qa.debian.org/developer.php?login=shibuuuu5@gmail.com)

* lithammer-fuzzysearch: debian unstableに入った。1.1.3への更新済み。
* 0xax-notificator: ITP済み。exampleのインポートパス問題はフィードバック済み。new queueにアップロード済み。
* erroneousboat-termui: ITP済み。
* slack-go-slack: ITP済み。テストの問題の切り分け中。
* slack-term: ITP済み。

**Comment by kenhys** [comment]
@sivchari 
10/06(水) 11:30-13:30 JST実施に変更してもらえませんか？
↑への変更でOKかどうか、もし都合が悪いようなら教えてください。

**Comment by kenhys** [comment]
ping @sivchari

**Comment by sivchari** [comment]
大丈夫です！

**Comment by kenhys** [comment]
@sivchari 確認ありがとうございます！

**Comment by kou** [comment]
@sivchari 聞こえますか！？入り直してもらったほうがいいかも！

**Comment by kou** [comment]
@sivchari 直ってないかも！どうしよう！

**Comment by kou** [comment]
@sivchari 最終レポートのpull request先は https://github.com/oss-gate/oss-gate.github.io/pulls です！
例： https://github.com/oss-gate/oss-gate.github.io/pull/106
