### ISSUE TITLE
2021-08: 11/21(日) のDebian勉強会で実施報告をする

### ISSUE THREAD

**Issue by kenhys** [oss-gate/on-boarding#28]
開催日時: 11/21(日) 14:00-16:00 (イベントページはあるが、参加登録ページは11月なのでまだない)

イベントに関するページ

[2021年11月 東京エリア・関西合同Debian勉強会（オンライン開催）](https://tokyodebian-team.pages.debian.net/2021-11.html)

そのうち https://debianjp.connpass.com/ につくられるはず。

* 発表者: @kenhys, @sivchari 
* 発表資料について: それぞれ発表資料を用意する想定(勉強会に参加していない人もあとから資料を参照できるようにしたいため。
* 発表時間の枠は各自15分くらい。(それより短くなっても良い)

* 発表内容について
  * @kenhys OSS Gateオンボーディングプロセス全体と工夫したこととか、雑多な内容を話す予定
  * @sivchari  新人の立場で得た学びとか、はじめてDebianのパッケージングに飛び込んだ人の意見をいろいろ話してもらえるとよい

**Comment by kenhys** [comment]
以前 https://gihyo.jp/admin/clip/01/ubuntu-topics/202107/30 のその他のニュースでとりあげてもらった。
MLで事前に予定を流すのと同時に  Ubuntu Weekly Topicsのその他のニュースで言及してもらえないか相談しよう。

**Comment by kenhys** [comment]
相談してみている。 https://twitter.com/kenhys/status/1443498527909285889

**Comment by yoshimotoyuk** [comment]
@sivchari さん
こんにちは～
季節の変わり目ですが体調などお変わりないですかー？
月も替わりそうなので、レポートどんな感じかな・・とおもい、ご連絡してみました。

Debian勉強会も11月なので、レポート含め、最近のご様子うかがえると幸いです。
よろしくお願いいたします！

**Comment by sivchari** [comment]
お疲れ様です！
インターンとConference等の資料作りで少しバタバタしております。
今週末にdebianのレポートを書けるよう調整しております 🙇

**Comment by yoshimotoyuk** [comment]
ありがとうございます！
教えていただき感謝です。無理のない範囲でどうぞよろしくお願いいたします。

もうちょっと近くなった勉強会の告知というか、こういうことはなすよ的なのを出す関係の話も進みだすと思いますのでー！

どうぞよろしくお願いいたします　m(_ _),m

**Comment by kenhys** [comment]
Ubuntu Weekly Topics 11/12(金)の「その他のニュース」でとりあげてもらう文言案


継続的にOSS開発に関わる仲間を増やすための活動[OSS Gateオンボーディング](https://oss-gate.github.io/on-boarding/)が無事に終了しました！
 [約2か月の期間中に着実にDebianパッケージ開発へ踏み出してもらえました。](https://oss-gate.github.io/report/on-boarding/2021/10/08/on-boarding-2021-08-kenhys.html) 
皆さんの[告知協力](https://gihyo.jp/admin/clip/01/ubuntu-topics/202107/30)ありがとうございました！
新しい人と一緒だから気づくことなど、詳しいことは11/21(日)開催の2021年11月 東京エリア・関西合同Debian勉強会（オンライン開催）で発表予定です。
[イベントページから参加申し込み](https://debianjp.connpass.com/event/226360/)できるようになっているので、ぜひご参加ください！

Markdown原稿
```
継続的にOSS開発に関わる仲間を増やすための活動[OSS Gateオンボーディング](https://oss-gate.github.io/on-boarding/)が無事に終了しました！
 [約2か月の期間中に着実にDebianパッケージ開発へ踏み出してもらえました。](https://oss-gate.github.io/report/on-boarding/2021/10/08/on-boarding-2021-08-kenhys.html) 
皆さんの[告知協力](https://gihyo.jp/admin/clip/01/ubuntu-topics/202107/30)ありがとうございました！
新しい人と一緒だから気づくことなど、詳しいことは11/21(日)開催の2021年11月 東京エリア・関西合同Debian勉強会（オンライン開催）で発表予定です。
[イベントページから参加申し込み](https://debianjp.connpass.com/event/226360/)できるようになっているので、ぜひご参加ください！
```

**Comment by yoshimotoyuk** [comment]
あ！ありがとうございました！！

**Comment by kenhys** [comment]
@sivchari jitsiのURLはイベントの参加者にのみ公開されているので、
https://debianjp.connpass.com/event/226360/ に当日までに参加登録しておいてくださいな。

**Comment by yoshimotoyuk** [comment]
直前にもあいていたらこっそり参加申し込みしてみようかな・・・

**Comment by kenhys** [comment]
@yoshimotoyuk まず参加枠が埋まることはないので、空いているかどうかは気にせず参加登録しちゃってください。(うまるくらい登録された状態は見てみたいものですが。。。)

**Comment by yoshimotoyuk** [comment]
@kenhys  だれだこいつっ！？ってざわつきません？

**Comment by kou** [comment]
初参加の人にそんな対応をしていたらそんなコミュニティーはすぐに廃れるでしょうね。。。

**Comment by yoshimotoyuk** [comment]
そうですよね。
とりあえず申し込みましたっ！

**Comment by kenhys** [comment]
勉強会の案内をdebian-usersとubuntu-jpに流しておいた。発表資料つくらなきゃ。

https://lists.debian.or.jp/pipermail/debian-users/2021-November/000748.html
https://lists.ubuntu.com/archives/ubuntu-jp/2021-November/006493.html

**Comment by kenhys** [comment]
@sivchari https://slide.rabbit-shocker.org/authors/kenhys/tokyodebian-oss-gate-onboarding-202111/ 多少手をいれるかもしれませんが、だいたいこんな感じの内容を話す予定です。というのを先に共有しておきます。

**Comment by kenhys** [comment]
@sivchari 11/21(日)の準備は大丈夫そうでしょうか? もし都合が悪くなったりというのであれば早めにお知らせください。

**Comment by sivchari** [comment]
連絡遅くなりごめんなさい。
こちら発表の目安時間どのくらいでしょうか？

**Comment by kenhys** [comment]
@sivchari 

> 14:20-15:00 セミナー1：「OSS Gateオンボーディング実施報告」（発表者：林さん、しぶちゃりさん）

枠自体は↑です。私は15-20分くらいを予定しています。@sivchari さんも同じくらいでどうでしょうか。

実際に体験した @sivhari さんの話のほうが大事なので、もっと話せる！なら私の方はすこし説明を省略して
あとで資料みてね、ということにして @sivchari さんのほうに多く時間を取るようにします。

なので、これくらい欲しいですというのを教えてください。
セミナー2がまだ決まってなさそうなので、もしかしたらそっちの時間ももらえるかもしれませんし。

**Comment by sivchari** [comment]
明日資料作れるので、一回リハーサルしてみてご連絡する形でよろしいでしょうか？

**Comment by kenhys** [comment]
@sivchari 

わかりました！それでお願いします。
(もっとはやく確認しておいたほうがよかったですね、すみません。)

**Comment by sivchari** [comment]
いえ！こちらの確認遅れでごめんなさい！
今日中に最終レポートはnoteにuploadします

**Comment by kenhys** [comment]
@sivchari 

わかりました！よろしくおねがいします！

**Comment by sivchari** [comment]
https://note.com/sivchari/n/ndd8d02477759

こちら書きました！最終レポートはどのように共有すればよろしいでしょうか？

また登壇の際の資料は慣れているGoogle Slideで作成させていただきたいのですが、よろしいでしょうか？

**Comment by kenhys** [comment]
2021年11月20日(土) 2:26 sivchari ***@***.***>:

> https://note.com/sivchari/n/ndd8d02477759
>
> こちら書きました！最終レポートはどのように共有すればよろしいでしょうか？
>

https://github.com/oss-gate/oss-gate.github.io/tree/master/_posts
こちらに追加してください！直接コミットできないかもしれないのでそのときはPRだしてください。


また登壇の際の資料は慣れているGoogle Slideで作成させていただきたいのですが、よろしいでしょうか
>

はい、特に指定はないのでそれでよいです。

**Comment by sivchari** [comment]
20分で大丈夫です！

**Comment by kenhys** [comment]
@sivchari わかりました!

**Comment by kenhys** [comment]
@sivchari さんの最終レポートへのリンクを貼っておきました。
https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/

**Comment by sivchari** [comment]
明日家のwifi工事が入るらしく、途中で抜けてしまう可能性があるのですが大丈夫でしょうか？

**Comment by kenhys** [comment]
14:00-16:00の時間すべて参加でなくても大丈夫です。
途中で抜けたりは気にしなくてよいです。

発表の時間はずらした方がよいですか？

私の後に話してもらうつもりだったので、
14:40頃から15 :00あたりなのですが。

あるいは、順番を入れ替えて先に話してもらうのでもよいです。


2021年11月21日(日) 2:52 sivchari ***@***.***>:

**Comment by kenhys** [comment]
発表終わり。
お疲れ様でした。

@sivchari ありがとうございました！

**Comment by kenhys** [comment]
@sivchari 

発表資料のURLを共有してもらえますか？
https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/ で紹介したいと思っています。
