### ISSUE TITLE
MariaDB Server developmentの参加者募集告知について

### ISSUE THREAD

**Issue by yoshimotoyuk** [oss-gate/on-boarding#30]
### 前提条件

次のOSS Gateオンボーディングの課題[MariaDB Server のバグ修正および機能開発](https://github.com/oss-gate/on-boarding/pull/29) に関して、参加者募集を行うにあたり、どのような場所でいつから告知を行うのかの整理を行う。

参考：第1回のDebian開発時の募集告知の流れ
* 先輩のTwitterで投稿
* 先輩がDebian勉強会（オンライン）で説明
* 先輩のTwitterの投稿をDebianコントリビューターの諸先輩や、コミュニティTwitterでリツイート

1週間ほどして、反応がなかったので
* Debian/Ubuntuメーリングリストに投稿　[参考]　https://github.com/oss-gate/on-boarding/issues/14

→　メーリングリストから、関係している別のコミュニティのSlackなどで告知されて応募が最終的に6件。
→　選考された応募者の方は、slack termをDebianにパッケージしたいという希望

### 実施内容

 募集開始の告知

### 完了条件

募集告知の完了　及び　申し込みが一定数に達したとき。

**Comment by nayuta-yanagisawa** [comment]
とりあえず思いついた告知先: Twitter, mysql-casual Slack #general_ja, MariaDB Community Slack #general_ja など。

**Comment by yoshimotoyuk** [comment]
ありがとうございます！
その他に可能性としてあるのは、（OSS Gate）Gitter　https://gitter.im/oss-gate/general/
かなと思っていました。

あとは、前回の流れでいうと開発者のメーリングリストがあると思うんですが、MariaDB https://launchpad.net/~maria-developers 　は、開発者になってみたい方がいらっしゃる感じとはちょっと違いますか？

**Comment by nayuta-yanagisawa** [comment]
Gitter はよさそうですね。

https://launchpad.net/~maria-developers にいるのは開発者か開発者だった人が多いと思います。昔からの人が多く参加しているイメージで、新人はいなさそうです。

**Comment by kou** [comment]
TwitterでMySQL界隈の人に相談してきます！

**Comment by nayuta-yanagisawa** [comment]
https://twitter.com/NayutaYanagisaw/status/1485600256834170882

**Comment by yoshimotoyuk** [comment]
ありがとうございます！
反応ありますね。応募がきたら、applicationのリポジトリに順にissueを立てていきます。

**Comment by yoshimotoyuk** [comment]
1月29日にOSS Gateワークショップという、OSS開発の第1歩をやってみる場　https://oss-gate.doorkeeper.jp/events/125414
があるので、そこでちょっと告知できるか聞いてみようと思います。
参加されている方が申し込むというよりは、そういう方がツイートしたりしてくれたら広がるんじゃないかな。
という希望的観測で、まだ、私の妄想です。

**Comment by kou** [comment]
日本MySQLユーザ会会のイベントはどうかな！？と思ったけど直近では開催予定はなさそうだった。
https://mysql.connpass.com/

**Comment by yoshimotoyuk** [comment]
OSS Gateワークショップの締めの会の場所で紹介してきます！。

**Comment by nayuta-yanagisawa** [comment]
ありがとうございます！

**Comment by kou** [comment]
https://twitter.com/yoku0825/status/1485558035515084801

MySQLユーザ会のメーリングリスト http://www.mysql.gr.jp/ml.html というアイディアをもらった。

@nayuta-yanagisawa MySQLユーザ会のメーリングリストってsubscribeしています？もしsubscribeしていたら告知してみませんか？もしsubscribeしていなかったら私が告知しておこうかと思っています。（私はすでにsubscribeしている。）

**Comment by nayuta-yanagisawa** [comment]
@kou してないです。お手数ですが、お願いできますか？

**Comment by kou** [comment]
http://www.mysql.gr.jp/mysqlml/mysql/msg/16687

告知してきました！

**Comment by nayuta-yanagisawa** [comment]
ありがとうございます！

**Comment by nayuta-yanagisawa** [comment]
自分が共同主査している RDBMS の論文輪読会で告知しました。

**Comment by kou** [comment]
さすがです！

**Comment by kou** [comment]
告知は終わった。
