### ISSUE TITLE
MariaDBプロジェクトふりかえりMTG日程調整

### ISSUE THREAD

**Issue by yoshimotoyuk** [oss-gate/on-boarding#34]
### 前提条件

OSS Gateオンボーディング開催中は、開催期間の中間で、振り返りMTGを行う。
https://oss-gate.github.io/on-boarding/process/meeting/

現在実施中：　[MariaDB Server のバグ修正および機能開発](https://oss-gate.github.io/on-boarding/proposals/2022-03/nayuta-mariadb-server/)

### 実施内容

そろそろふりかえりMTGを実施させていただきたく、
スケジュールの調整をお願いできればとおもいます！よろしくお願いします。

候補日：2022/5/9,10,12,13のどこか
時間：　15:00-16:30（10:00pm-12:00am PST）
参加予定：
@nayuta-yanagisawa  @rdtr @kou @yoshimotoyuk 

ミーティングについて：https://oss-gate.github.io/on-boarding/process/meeting/

参考（前回分）：[ふりかえりMTGメモ](https://oss-gate.github.io/on-boarding/proposals/2021-08/kenhys-maintain-debian-packages/meeting-2021-08-31.html)

日程が決まり次第、e-mailでjisi MTG　URLお送りします。
よろしくお願いします。

### 完了条件

ふりかえりMTGの日程が決まり次第

**Comment by yoshimotoyuk** [comment]
もし候補日がご都合悪い場合、可能そうな候補日をいただけますと幸いです。
よろしくお願いします。

**Comment by nayuta-yanagisawa** [comment]
自分はいまのところいつでも大丈夫です。

**Comment by kou** [comment]
私もどれでも大丈夫です！

**Comment by yoshimotoyuk** [comment]
@rdtr さん
恐縮ですがご都合の良いスケジュールお教えいただけると幸いです。
よろしくお願いいたします。

**Comment by rdtr** [comment]
すみません、メールでこのやりとりを見た記憶がしていたのですが、見つからなくてそのままになってました..

今の日にちでいうと皆さんのご都合が大丈夫であれば5/13(5/12 PDT)でお願いしたいです。

**Comment by yoshimotoyuk** [comment]
ご連絡ありがとうございます。
あっちもこっちもでご連絡してしまったのでメール通知的には複数お届けになっていたかもしれません・・・

@kou @nayuta-yanagisawa 
みなさまご都合変わらずでOKでしたら13日15:00-16:30でお願いできればと思いますがご査収よろしくお願いいたします。

**Comment by kou** [comment]
大丈夫です！

**Comment by nayuta-yanagisawa** [comment]
大丈夫です！

**Comment by nayuta-yanagisawa** [comment]
できれば15:00-がいいです。

**Comment by yoshimotoyuk** [comment]
@nayuta-yanagisawa @rdtr @kou 

はい
では　13日15:00-16:30（10:00pm-12:00am PST）にてお願いします！
MTG URLは、別途メールでそれぞれ皆様にお送りしたので問題がありましたらご連絡ください。

**Comment by pst** [comment]
Please stop pinging me by writing @pst. Thanks

**Comment by kou** [comment]
Oh, sorry. We stop it.

**Comment by yoshimotoyuk** [comment]
こちらは完了。
