### ISSUE TITLE
2022-06まとめミーティング日程調整

### ISSUE THREAD

**Issue by yoshimotoyuk** [oss-gate/on-boarding#38]
### 前提条件

2022年4月から始まったオンボーディングもそろそろ予定していた2か月となりますので最終MTGのスケジュールを調整します。

これまでの作業や、やり方などを振り返るミーティングを行い、オンボーディングの完了とします。
これからも継続的に参加しやすい状況になったかなどを確認します。

【日程】
6/30（木） 7/1 (金)  7/4(月）7/5（火）7/6(水）

【時間】
日本時間15：00-
(西海岸夏時間) 23:00-

### 実施内容

* 後半の作業振り返り
* 最終レポートに関する確認
* 発表などをするかなどの確認
* 今後の改善点などの意見交換

* https://github.com/oss-gate/on-boarding/pull/37
前回のミーティングレポートの確認

### 完了条件

新人、先輩、運営のメンバーでまとめのミーティングを開催する

**Comment by kou** [comment]
私はいつでも大丈夫です！

**Comment by yoshimotoyuk** [comment]
もしかしたらサマータイムの巻き戻りがある気がしていますが、ご連絡次第で時間は多少前後するということでおねがいします！

**Comment by yoshimotoyuk** [comment]
@nayuta-yanagisawa @rdtr 
お世話になります！
ご都合お伺いできますと幸いですっ。

**Comment by rdtr** [comment]
@yoshimotoyuk @nayuta-yanagisawa 
すみません、仕事でトラブル対応に入ってしまって返信が遅くなってしまいました...加えて、柳澤さんとは話していたのですが会社の方で自分のPRが検知されて、会社を通してのPRにしてくれ（いったん弊社内でのレビューがあります、ほぼプロセスとしてだけと思いますが）という調整も入りました。
今日でまたオンコールあけるので時間がとれるはずです.

柳澤さんとはこちらもすでにお話していたのですが, ちょっと時間が取れていなかったので, プロジェクトを今月末までに延長してInnoDB周りは厳しいので一つtopicとしてJSON tableまわりの理解を深めたところで終わりにしようかなという話にしています。

こちらの6/30（木）（日本での7/1)あたりの同じ時間等をまとめミーティングの日にちに変更していただくことは可能でしょうか？都合がつかなさそうであればその前後でも自分は問題ないです.

**Comment by kou** [comment]
わかりました！

では、6/30（木）（日本での7/1)か翌週のどこかで調整しましょう！

@yoshimotoyuk 日時候補をまとめ直してもらえますか！？

**Comment by yoshimotoyuk** [comment]
@rdtr 　ご返信ありがとうございます！
もろもろ承知しました！お無理をなさらず・・・

@kou @nayuta-yanagisawa 
いったん候補日を設けました。
まだちょっと先なので、仮の日程として挙げています。
夏時間で結構夜も遅めなので金曜がいいのかな？と思ったりはしています。

よろしくお願いします！

**Comment by nayuta-yanagisawa** [comment]
夜でしたら、月木金希望です！

**Comment by yoshimotoyuk** [comment]
すみません！わかりづらいことをしていました！
あかぎさんの夜の時間が結構遅いという意味でした！

15時だと23時スタートだと気が付きまして・・・

けれどご都合は把握しました！ありがとうございます。

**Comment by nayuta-yanagisawa** [comment]
なるほど。日本時間の昼でしたら、火曜日以外は大抵大丈夫ですmm

**Comment by kou** [comment]
> 6/30（木） 7/1 (金) 7/4(月）7/5（火）7/6(水）

どれでも大丈夫です。が、日本での7/1以降がよさそうということなので日本での6/30は候補外じゃないかと思いました。

**Comment by kou** [comment]
@rdtr 予定はいかがでしょうか！

**Comment by rdtr** [comment]
@kou 
申し訳ありません、子どもが学校で２週連続COVIDの濃厚接触で自宅’隔離になってしまってこちらに戻ってくる余力がありませんでした...

最終成果みたいなものをどうするのか @nayuta-yanagisawa さんともう一度話そうという方向でいて、今夜時間が取れたので、そこから一度仕切り直して再度最後のミーティングに持っていく形でも大丈夫でしょうか？
3-4週間後くらいをターゲットにしたいと今は考えています. 

子どもが陽性でない限りは感染者が出ようが学校行っても良い方向に変わった（変わっていいのか？という疑問はありつつ.. )ので、陽性にならない限りはここからは大丈夫だと思います. だらだらとプロジェクトの終わりが伸びてしまっていて申し訳ありませんが、ご確認をよろしくお願いします。

**Comment by kou** [comment]
@rdtr なんと！そうだったのですね。。。急かしてしまってすみませんでした。。。

急いで終わらせることよりも赤木さんがこの取り組みのあとも継続的にMariaDBの開発に参加するようになることの方が大事なので当初の予定より延長するので問題ありません！

**Comment by yoshimotoyuk** [comment]
こんにちは！
あっという間に８月になりました・・・
もし、まとめミーティングのスケジュールなど決められそうでしたらお教えいただければと思います！

どうぞよろしくお願いいたします。


それにしても、毎日暑いですねぇ・・・

**Comment by yoshimotoyuk** [comment]
@rdtr さん　@nayuta-yanagisawa さん　
ご都合わかりましたらお教えいただけますと幸いです！
どうぞよろしくお願いいたします。
（ちなみに弊社は、お盆お休みなどは特にありません）

**Comment by nayuta-yanagisawa** [comment]
お返事遅くなりすみません。あと1つ issue を解決したら終わりにしようということで話がまとまったので、お盆明けか8月末ぐらいがよさそうだなと思っています。

**Comment by kou** [comment]
わかりました！

**Comment by yoshimotoyuk** [comment]
承知しました！ありがとうございます。

**Comment by rdtr** [comment]
すみません、こちらの都合で遅れてしまっていて申し訳ないのですが
あと１つissueをやりきって, ブログに開発の手順や学んだことをまとめるところまではやりたいので
8/18か25(こちらの19か26)の週あたりで最後の報告ができればと思っています。

18は日本でお盆明けでバタバタしているかもですかね？

**Comment by kou** [comment]
大丈夫です！
この取り込みが終わった後も引き続きMariaDBの開発に参加するにすることを目指しているので、それにつながるなら延長しても大丈夫です！

@yoshimotoyuk また候補日をリストアップしてもらえますか？

**Comment by yoshimotoyuk** [comment]
ご確認ありがとうございます！

須藤さんと私のスケジュール的には
日本時間
18日    15:30~ 
22日　15:30~
23日　15:30～
が都合がよさそうです。（25日は調整中の案件がありそうで流動的です）

18日が第一候補でいかがでしょうか？

**Comment by nayuta-yanagisawa** [comment]
18, 22 であればいつでも大丈夫です。23 は他用により参加できません。

**Comment by yoshimotoyuk** [comment]
ありがとうございます！
18日が濃厚そうな気がしています！

**Comment by yoshimotoyuk** [comment]
@rdtr さん
18日15：00～（日本時間）で大丈夫そうでしょうか？

**Comment by rdtr** [comment]
了解です、18日15:00@JPT=17日23:00@PDTで大丈夫です！
おそらくタスク的には最後までいかずはみ出す気がしますが、どのみち継続するので一旦ここで最終報告とさせていただきたいと思います。

**Comment by nayuta-yanagisawa** [comment]
私もその時間で大丈夫です。

**Comment by yoshimotoyuk** [comment]
ありがとうございます！
ではこちらで決定とさせていただきます！

いったんのできてる範囲までの確認と、今後も継続していけそうか。
継続していけるようにするにはこんなこともあればよかったみたいなことが話せたらいいなと思っています！

ミーティングURLは一応またメールで送信させていただきます！

**Comment by yoshimotoyuk** [comment]
@nayuta-yanagisawa さん　@rdtr　さん 

本日よろしくお願いします！
ふりかえり＆まとめミーティングを進行するにあたり、作業をしたときの記録（日報）について、どこかに記録されているようでしたら、共有いただくことは可能でしょうか？

よろしくお願いいたします。

**Comment by kou** [comment]
参考：前回のミーティングで、コミットするのは面倒だからissueに書くのを試してみる？ということで https://github.com/oss-gate/on-boarding/issues/35 と https://github.com/oss-gate/on-boarding/issues/36 を用意してはいました。

https://oss-gate.github.io/on-boarding/proposals/2022-03/nayuta-mariadb-server/2022-05-13-meeting.html

> * Gitにpushするのが日報の更新の障壁になっGitにpushするのが日報の更新の障壁になっている
>    * 一回、issueに書いて、コメントでのやりとりで行う形をためしてみる

**Comment by rdtr** [comment]
すみません、ミーティングでも話しますが隙間時間に切れ切れに作業をやっていくような形になっていたので後半に関してはきちんとした形で日報を残せていません..

Worklogをどうやって残せるかは自分の中でも課題です

**Comment by yoshimotoyuk** [comment]
ミーティングありがとうございました！
TiDB少しは日本人のコントリビューターの方もいるみたいですね
https://developer.tidb.io/people/contributor

**Comment by kou** [comment]
* 最終レポート： #39
* ログ： #40
